# platform = multi_platform_ol
# reboot = false
# strategy = restrict
# complexity = high
# disruption = medium

- name: "Read files with incorrect hash"
  command: rpm -V crypto-policies
  register: files_with_incorrect_hash
  changed_when: False
  failed_when: files_with_incorrect_hash.rc > 1
  check_mode: False

- name: "Reinstall packages of files with incorrect hash"
  command: "{{{ pkg_manager }}} reinstall -y crypto-policies"
  when:
    - files_with_incorrect_hash.stdout_lines is defined
    - (files_with_incorrect_hash.stdout_lines | length > 0)
