# platform = multi_platform_all

- name: Ensure interactive local users are the owners of their respective initialization files
  ansible.builtin.lineinfile:
    dest: /etc/group
    backrefs: yes
    regexp: '(^shadow:[^:]*:[^:]*:)([^:]+$)'
    line: '\1'
