# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

{{{ ansible_pam_faillock_enable(rule_title=rule_title) }}}
{{{ ansible_pam_faillock_parameter_value("silent", authfail=False, rule_title=rule_title)}}}
