# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

{{% if 'rhel' not in product and product != 'fedora' %}}
- name: Require single user mode password
  lineinfile:
      create: yes
      dest: /usr/lib/systemd/system/rescue.service
      regexp: "^#?ExecStart="
      {{% if product in ["sle12", "sle15", "slmicro5"] or 'ol' in families -%}}
      line: "ExecStart=-/usr/lib/systemd/systemd-sulogin-shell rescue"
      {{%- else -%}}
      line: 'ExecStart=-/bin/sh -c "/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"'
      {{%- endif %}}
{{% else %}}
- name: "{{{ rule_title }}} - Require emergency user mode password"
  community.general.ini_file:
    path: "/etc/systemd/system/rescue.service.d/10-oscap.conf"
    section: "Service"
    option: "ExecStart"
    value: "-/usr/lib/systemd/systemd-sulogin-shell rescue"
{{% endif %}}
